[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
alloy = { version = "0.12.5", features = ["full"] }
dotenv = "0.15.0"
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["full"] }
env_logger = "0.11.7"