[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
alloy = { version = "0.11.1", features = ["full"] }
dotenv = "0.15.0"
serde = "1.0.218"
tokio = { version = "1.43.0", features = ["full"] }
